spring.application.name=catalog-service

# Database Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dropforge}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:pass2word}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Security Settings (Looks for Mac env var, falls back to default if not found)
app.security.jwt-secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}