sonar.projectKey=Vaibhav040_dropship-platform
sonar.organization=vaibhav040

sonar.projectName=dropship-platform
sonar.projectVersion=1.0

sonar.sources=storefront-ui/src,catalog-service/src/main/java,order-service/src/main/java
sonar.tests=catalog-service/src/test/java,order-service/src/test/java

sonar.exclusions=**/node_modules/**,**/target/**,**/.vite/**
sonar.sourceEncoding=UTF-8