apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: dropship
  labels:
    app: order-db
spec:
  type: ClusterIP
  selector:
    app: order-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-db
  namespace: dropship
  labels:
    app: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: postgres
        image: postgres:15.3-alpine
        imagePullPolicy: IfNotPresent
        resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: POSTGRES_DB
            value: "dropship"
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 15
          periodSeconds: 10