name: Dropforge CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_frontend:
    name: Build Storefront UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./storefront-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './storefront-ui/package-lock.json'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build Vite React App
        run: npm run build

  build-catalog-service:
    name: Build Catalog API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalog-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile maven .jar
        run: mvn clean package -DskipTests

  build-order-service:
    name: Build Order API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile maven .jar
        run: mvn clean package -DskipTests

  verify-builds:
    name: Verify Builds
    needs: [build_frontend, build-catalog-service, build-order-service]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test Infrastructure Build
        run: docker compose build

  build-and-push-ecr:
    name: Build & Push Image to ECR
    needs: verify-builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push order-service Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dropship-order-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building order-service image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITRY:$IMAGE_TAG ./order-service
          echo "Pushing order-service image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build and Push Storefront-ui Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dropship-storefront-ui
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building storefront-ui image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./storefront-ui
          echo "Pushing storefront-ui image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build and Push catalog-service Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dropship-catalog-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building catalog-service image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./catalog-service
          echo "Pushing catalog-service image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG